homeassistant:
  customize: !include customize.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate


http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.10.1      # Add the IP address of the proxy server
    - 172.30.33.0/24
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

group: !include groups.yaml
mqtt: !include_dir_merge_named mqtt
homekit:

recorder:
  db_url: !secret recorder_db_url
